name: Deploy Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to VPS
        run: |
          cd /opt/apps/RudyFront
          git pull
          ng build
          sudo systemctl reload nginx
